runtime: python
env: flex
entrypoint: gunicorn -t 300 -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

